/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.datafusion.view;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author Matheus
 */
public class FormularioMapeamentoSwing extends javax.swing.JFrame {

    /**
     * Creates new form FormularioMapeamentoSwing
     */
    private JTextField nomeEntidadeField;
    private List<EstruturaCampoPanel> estruturaCampos;

    public FormularioMapeamentoSwing() {
        super("Formulário de Mapeamento");
        initComponents();

        nomeEntidadeField = new JTextField(20);
        estruturaCampos = new ArrayList<>();

        JButton adicionarCampoButton = new JButton("Adicionar Campo");
        adicionarCampoButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                adicionarEstruturaCampo();
            }
        });

        JPanel panel = new JPanel(new GridBagLayout());
        GridBagConstraints gbc = new GridBagConstraints();
        gbc.insets = new Insets(5, 5, 5, 5);

        gbc.gridx = 0;
        gbc.gridy = 0;
        panel.add(new JLabel("Nome da Entidade:"), gbc);

        gbc.gridx = 1;
        gbc.gridy = 0;
        panel.add(nomeEntidadeField, gbc);

        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.gridwidth = 2;
        panel.add(adicionarCampoButton, gbc);

        setLayout(new BorderLayout());
        add(panel, BorderLayout.NORTH);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        pack();
        setLocationRelativeTo(null);
    }

    private void adicionarEstruturaCampo() {
        EstruturaCampoPanel estruturaCampo = new EstruturaCampoPanel();
        estruturaCampos.add(estruturaCampo);

        JPanel panel = new JPanel(new GridBagLayout());
        GridBagConstraints gbc = new GridBagConstraints();
        gbc.insets = new Insets(5, 5, 5, 5);

        gbc.gridx = 0;
        gbc.gridy = estruturaCampos.size() + 1;
        panel.add(estruturaCampo, gbc);

        getContentPane().add(panel, BorderLayout.CENTER);
        pack();
    }

    public static void main(String[] args) {
        SwingUtilities.invokeLater(new Runnable() {
            @Override
            public void run() {
                new FormularioMapeamentoSwing().setVisible(true);
            }
        });
    }

    private class EstruturaCampoPanel extends JPanel {

        private JTextField nomeCampoField;
        private JCheckBox obrigatorioCheckBox;
        private JCheckBox chavePrimariaCheckBox;
        private JComboBox<String> tipoCampoComboBox;

        public EstruturaCampoPanel() {
            nomeCampoField = new JTextField(10);
            obrigatorioCheckBox = new JCheckBox("Obrigatório");
            chavePrimariaCheckBox = new JCheckBox("Chave Primária");
            tipoCampoComboBox = new JComboBox<>(new String[]{"Texto", "Número", "Data"});

            setLayout(new FlowLayout(FlowLayout.LEFT));

            add(new JLabel("Nome do Campo:"));
            add(nomeCampoField);
            add(obrigatorioCheckBox);
            add(chavePrimariaCheckBox);
            add(new JLabel("Tipo do Campo:"));
            add(tipoCampoComboBox);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
